use online_food_del;

-- 1.Total Orders per City
SELECT r.city, COUNT(o.order_id) as total_orders
FROM restaurants r JOIN orders o ON o.restaurant_id=r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;
-- Jaipur,Hyderbad, Delhi has highest no of food orders compare to others
-- active markets
-- focus marketing effect, special offer
-- expansion strategies
-- improve operations in other cities


-- 2.Revenue Generated by Each Food Item
SELECT m.item_name, SUM(m.price*od.quantity) as total_Revenue
FROM menu_items m JOIN order_details od ON od.item_id=m.item_id
GROUP BY m.item_name
ORDER BY total_Revenue DESC;
-- insight-- best performing food item
-- Aloo Paratha, fish Curry, Hakka Noodles the top 3 food item generates total revenue
-- Promote it prominetly an app
-- ensure consistent availabitlity and faster delivery

-- 3.Top 5 Spending Customers
SELECT c.customer_name, SUM(m.price) as total_spend
FROM customers c 
JOIN orders o ON o.customer_id=c.customer_id
JOIN menu_items m ON m.restaurant_id=o.restaurant_id
GROUP BY c.customer_name
ORDER BY total_spend DESC
LIMIT 5;
-- insight-- 
-- Sai Verma, Vihaan Patel,, Reyansh Verma, Arjun Mehta, Muhammad Patel	are top 5 spending customers name
-- top 5 customers spend price between 53000 to 68000

-- 4. Restaurant-wise Order Count
SELECT r.restaurent_name, COUNT(o.order_id) as total_orders
FROM restaurants r JOIN orders o ON o.restaurant_id=r.restaurant_id
GROUP BY r.restaurent_name
ORDER BY total_orders DESC;
-- Golden Garden, Spice Palace, Tasty Bistro has taken most no of orders 
-- -- active markets
-- focus marketing effect, special offer
-- expansion strategies to order taking

-- 5. Average Order Value by City
SELECT r.city, sum(m.price*od.quantity)/COUNT(o.order_id)as Avg_order_value
FROM restaurants r 
JOIN orders o ON o.restaurant_id=r.restaurant_id
JOIN order_details od ON od.order_id=o.order_id
JOIN menu_items m ON m.item_id=od.item_id
GROUP BY r.city
ORDER BY Avg_order_value DESC;
